export class User {
  username: string = ""
  password: string = ""
  userType: string = ""
  securityQuestion: string = ""
  securityAnswer: string = ""
  name: string = ""
  surname: string = ""
  gender: string = ""
  address: string = ""
  phone: string = ""
  email: string = ""
  profilePicture: string = ""
  schoolType: string = ""
  currentGrade: string = ""
}
